### ISSUE TITLE
Base theme: 

### ISSUE THREAD

**Issue by Adriana-Morera** [wet-boew/theme-base#126]
What about Spanish language???

**Comment by LaurentGoderre** [comment]
The toolkit does support Spanish but it seems like a bug is preventing it from being listed.

**Comment by LaurentGoderre** [comment]
Looks like a bug from grunt-i18n-csv

**Comment by Adriana-Morera** [comment]
Hi Laurent,
That's weird …  Hopefully someone can fix it [cid:image001.png@01D1696E.6120BEB0]
Thank you for your prompt reply and have a great day! ☺

Adriana Morera, BAccS, MBA-
Agent de projets, Direction générale de service aux citoyens
Service Canada / Gouvernement du Canada
adriana.morera@hrsdc-rhdcc.gc.ca<mailto:adriana.morera@hrsdc-rhdcc.gc.ca>  / Tél. :  819-654-2145

Project Officer, Citizen Service Branch
Service Canada / Government of Canada
adriana.morera@hrsdc-rhdcc.gc.ca<mailto:adriana.morera@hrsdc-rhdcc.gc.ca>  / Tel:  819-654-2145

**Comment by LaurentGoderre** [comment]
Ok, so it's not a bug with grunt-i18n-csv, and it appears the Spanish example are being generated but not linked from the index page.
